### ISSUE TITLE
Controller crashes and can't recover

### ISSUE THREAD

**Issue by rafaeltuelho** [redhat-cop/gitwebhook-operator#20]
I noticed the Controller crashes when it can't find the secret referenced by the `GitWebhook` CR

the `GitWebhook` status is:

```yaml
status:
  conditions:
    - lastTransitionTime: '2023-12-21T21:52:29Z'
      message: Secret "my-springboot-app-demo1-github-pat-webhook" not found
      observedGeneration: 1
      reason: reconcile_failed
      status: 'True'
      type: Failure
```

This situation may happen if Argo creates `GitWebhook` before the Secret. The Controller should handle the error and move on.

Controller crash log 
```
1.7031986259330854e+09 DEBUG reconcile started {"controller": "gitwebhook", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "GitWebhook", "GitWebhook": {"name":"my-springboot-app-demo1","namespace":"my-springboot-app-demo1-dev"}, "namespace": "my-springboot-app-demo1-dev", "name": "my-springboot-app-demo1", "reconcileID": "7a5dd6a2-3699-4524-a4a3-42df9ce07d9c", "instance": {"apiVersion": "redhatcop.redhat.io/v1alpha1", "kind": "GitWebhook", "namespace": "my-springboot-app-demo1-dev", "name": "my-springboot-app-demo1"}}
1.7031986259332082e+09 INFO Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference {"controller": "gitwebhook", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "GitWebhook", "GitWebhook": {"name":"my-springboot-app-demo1","namespace":"my-springboot-app-demo1-dev"}, "namespace": "my-springboot-app-demo1-dev", "name": "my-springboot-app-demo1", "reconcileID": "7a5dd6a2-3699-4524-a4a3-42df9ce07d9c"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ba27b]
goroutine 473 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1519060, 0x23d0d70})
/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x207
github.com/redhat-cop/gitwebhook-operator/api/v1alpha1/github.IsNotFound(...)
/home/runner/work/gitwebhook-operator/gitwebhook-operator/api/v1alpha1/github/webhook.go:119
github.com/redhat-cop/gitwebhook-operator/api/v1alpha1/github.(*GitHubWebHook).getHook(0xc001ea1b88, {0x1931e68, 0xc001e925a0})
/home/runner/work/gitwebhook-operator/gitwebhook-operator/api/v1alpha1/github/webhook.go:100 +0x17b
github.com/redhat-cop/gitwebhook-operator/api/v1alpha1/github.(*GitHubWebHook).deleteIfExists(0xc001ea1b88, {0x1931e68, 0xc001e925a0})
/home/runner/work/gitwebhook-operator/gitwebhook-operator/api/v1alpha1/github/webhook.go:205 +0x7c
github.com/redhat-cop/gitwebhook-operator/api/v1alpha1/github.(*GitHubWebHook).Delete(...)
/home/runner/work/gitwebhook-operator/gitwebhook-operator/api/v1alpha1/github/webhook.go:231
github.com/redhat-cop/gitwebhook-operator/controllers.(*GitWebhookReconciler).deleteWebhook(0x1933680?, {0x1931e68?, 0xc001e925a0?}, 0x16f9711?)
/home/runner/work/gitwebhook-operator/gitwebhook-operator/controllers/gitwebhook_controller.go:134 +0xb4
github.com/redhat-cop/gitwebhook-operator/controllers.(*GitWebhookReconciler).Reconcile(0xc0007ba390, {0x1931e68, 0xc001e92540}, {{{0xc000146560?, 0x10?}, {0xc00015a5d0?, 0x40f2a7?}}})
/home/runner/work/gitwebhook-operator/gitwebhook-operator/controllers/gitwebhook_controller.go:109 +0x378
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1931dc0?, {0x1931e68?, 0xc001e92540?}, {{{0xc000146560?, 0x162a6e0?}, {0xc00015a5d0?, 0x404bd4?}}})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002aa3c0, {0x1931dc0, 0xc000896a00}, {0x1570760?, 0xc000632760?})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002aa3c0, {0x1931dc0, 0xc000896a00})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:230 +0x325
```

**Comment by rafaeltuelho** [comment]
Actually, it seems the controller is crashing at this point here: https://github.com/redhat-cop/gitwebhook-operator/blob/main/api/v1alpha1/github/webhook.go#L119

I don't think it's related to the non-existing referenced Secret.

**Comment by rafaeltuelho** [comment]
I found the root cause of this issue.
If I specify the `gitHubAPIServerURL` as `https://api.github.com` (**without** ending with `/`) in the CR the github client returns an error and the `response` is `nil`. Thus, the line https://github.com/redhat-cop/gitwebhook-operator/blob/main/api/v1alpha1/github/webhook.go#L119 tries to access `nil` causing the panic.

The root cause is this little piece of logic here https://github.com/redhat-cop/gitwebhook-operator/blob/main/api/v1alpha1/github/webhook.go#L100 which can be fixed by simply switching `&&` (and) by `||` (or)

**Comment by raffaelespazzoli** [comment]
@rafaeltuelho can you make a contribution? So you can test directly with your use case? That line is indeed a bit suspicious. Should also the ! be removed from `!IsNotFound(response)`
